apiVersion: v2
name: payloadbox
description: Lightweight, self-hosted HTTP Request Inspector with a built-in web interface.
type: application
version: 0.0.2
appVersion: "0.0.6"
home: https://github.com/ByteFork/helm-charts
sources:
  - https://github.com/ByteFork/helm-charts
maintainers:
  - name: ByteFork
    url: https://github.com/ByteFork
dependencies:
  - name: common-app
    version: 0.0.1
    repository: https://bytefork.github.io/helm-charts
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/ByteFork/helm-charts
  artifacthub.io/images: |-
    - name: payloadbox
      image: ghcr.io/bytefork/payloadbox:0.0.4
